version: '3.4'

services:
  sourcingdb:
    container_name: sourcingdb
    restart: always
    volumes:
        - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
        - "27017:27017"

  rabbitmqmsapp:
    container_name: rabbitmqmsapp
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  sourcingsqldb:
    container_name: sourcingsqldb
    ports:
        - "1433:1433"
    environment:
      SA_PASSWORD: "3581vedat."
      ACCEPT_EULA: "Y"

  esourcing.products:
    container_name: esourcingproducts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ProductDatabaseSettings:ConnectionString=mongodb://sourcingdb:27017"
    depends_on:
      - sourcingdb
    ports:
      - "8001:80"
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets      
      - ${HOME}/.aspnet/https:/root/.aspnet/https/

  esourcing.sourcing:
    container_name: esourcingsourcing
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SourcingDatabaseSettings:ConnectionString=mongodb://sourcingdb:27017"
      - "EventBus:HostName=rabbitmqmsapp"
    depends_on:
      - sourcingdb
      - rabbitmqmsapp
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets      
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
      - "8002:80"


  esourcing.order:
    container_name: esourcingorder
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderConnection=Server=sourcingsqldb;Database=OrderDb;User Id=sa;Password=3581vedat.;"
      - "EventBus:HostName=rabbitmqmsapp"
    depends_on:
      - sourcingsqldb
      - rabbitmqmsapp
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets      
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
      - "8003:80"

