version: '3.4'

services:
  sourcingdb:
    container_name: sourcingdb
    restart: always
    volumes:
        - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
        - "27017:27017"

  esourcing.products:
    container_name: esourcingproducts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ProductDatabaseSettings:ConnectionString=mongodb://sourcingdb:27017"
    depends_on:
      - sourcingdb
    ports:
      - "8001:80"
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets      
      - ${HOME}/.aspnet/https:/root/.aspnet/https/


  esourcing.sourcing:
    container_name: esourcingsourcing
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SourcingDatabaseSettings:ConnectionString=mongodb://sourcingdb:27017"
    depends_on:
      - sourcingdb
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets      
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
      - "8002:80"

